const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const code=fs.readFileSync(path.join(__dirname,'../public/graph.js'),'utf8');
function setup(reduced=false,specimen=false){
 let draws=0,serial=0,resize,opened=0,cleanup,clock=0,nodePoint;const frames=new Map(),controls=new Map(),listeners=new Map(),timers=new Map(),documentListeners=new Map();let timerId=0,strokes=[];const handles=['a','b'].map(collection=>({dataset:{thread:collection},offsetWidth:100,offsetHeight:44,classList:{toggle(){}},style:{},clicks:0,click(){this.clicks++},addEventListener(type,fn){this[type]=fn},removeEventListener(type){delete this[type]}}));function advance(ms){clock+=ms;for(const [id,t] of [...timers])if(t.at<=clock){timers.delete(id);t.fn()}}
 const context=new Proxy({arc(x,y){nodePoint={x,y}},stroke(){strokes.push(context.strokeStyle)},clearRect(){draws++;strokes=[]},measureText(){return {width:30}},createRadialGradient(){return {addColorStop(){}}}}, {get:(o,k)=>o[k]||(()=>{})});
 const canvas={getContext:()=>context,parentElement:{clientWidth:600,clientHeight:500,querySelectorAll:()=>handles},style:{},addEventListener(type,fn,options){listeners.set(type,{fn,options})},removeEventListener(type){listeners.delete(type)},getBoundingClientRect:()=>({left:0,top:0}),setPointerCapture(){}};
 const sandbox={setTimeout(fn,ms){timers.set(++timerId,{fn,at:clock+ms});return timerId},clearTimeout(id){timers.delete(id)},performance:{now:()=>clock},window:{devicePixelRatio:3,innerWidth:600,matchMedia:()=>({matches:reduced,addEventListener(){},removeEventListener(){}})},document:{addEventListener(type,fn){documentListeners.set(type,fn)},removeEventListener(type){documentListeners.delete(type)},querySelector(id){if(!controls.has(id))controls.set(id,{});return controls.get(id)}},ResizeObserver:class{constructor(fn){resize=fn}observe(){resize()}disconnect(){}},requestAnimationFrame(fn){frames.set(++serial,fn);return serial},cancelAnimationFrame(id){frames.delete(id)}};
 vm.createContext(sandbox);vm.runInContext(code,sandbox);
 cleanup=sandbox.createTumbleweedGraph(canvas,[{id:'one',title:'One',kind:'note',collection:'a',topics:[]},{id:'two',title:'Two',kind:'note',collection:'b',topics:[]}],[{id:'edge',from:'one',to:'two',basis:'explicit'}],()=>{opened++;cleanup()},{specimen,groups:['a','b']});
 return {canvas,controls,frames,listeners,documentListeners,cleanup,handles,timers,get highlighted(){return strokes.includes('rgba(230,182,108,.95)')},get nodePoint(){return nodePoint},get camera(){return vm.runInContext('graphCamera',sandbox)},resize:()=>resize(),advance,settle(){for(let n=0;frames.size&&n<500;n++)this.flush();assert.equal(frames.size,0)},flush(ms=16){advance(ms);const pending=[...frames.values()];frames.clear();pending.forEach(fn=>fn(clock))},get draws(){return draws},get opened(){return opened}};
}
let g=setup();assert.equal(g.frames.size,1);g.resize();g.resize();assert.equal(g.frames.size,1);g.flush();assert.equal(g.draws,1);assert.equal(g.canvas.width,1200);console.log('PASS resize is coalesced and density capped');
for(let i=0;i<20;i++)g.controls.get('#rotate-left').onclick();assert.equal(g.frames.size,1);g.flush();assert.equal(g.draws,2);console.log('PASS repeated controls draw once per frame');g.settle();
for(let i=0;i<20;i++)g.canvas.onpointermove({clientX:-100,clientY:-100});assert.equal(g.frames.size,0);console.log('PASS unchanged empty hover does not redraw');
g.controls.get('#zoom-in').onclick();g.cleanup();assert.equal(g.frames.size,0);assert.equal(g.canvas.onpointermove,null);g.resize();assert.equal(g.frames.size,0);console.log('PASS disposal cancels work and detaches input');
g=setup();g.flush();g.canvas.onpointerdown({button:2,pointerId:1,clientX:100,clientY:100});g.canvas.onpointermove({clientX:-100,clientY:-100});assert.equal(g.frames.size,0);console.log('PASS secondary pointer does not rotate');
g.cleanup();

function event(id,x,y,type='touch'){return {pointerId:id,clientX:x,clientY:y,button:0,pointerType:type,prevented:false,preventDefault(){this.prevented=true}}}
g=setup();g.flush();g.canvas.onpointerdown(event(1,100,100));g.canvas.onpointerdown(event(2,200,100));g.documentListeners.get('visibilitychange')();g.canvas.onpointerdown(event(3,100,100));g.canvas.onpointermove(event(3,140,100));g.canvas.onpointerup(event(3,140,100));g.cleanup();assert.ok(Math.abs(g.camera.yaw-.42)<1e-12);assert.equal(g.camera.zoom,1);assert.equal(g.documentListeners.size,0);console.log('PASS returning after app switch starts a clean gesture without stale fingers');
g=setup();g.flush();const heldPoint=g.nodePoint;g.canvas.onpointerdown(event(1,heldPoint.x,heldPoint.y));g.documentListeners.get('visibilitychange')();g.advance(400);g.canvas.onpointerup(event(1,heldPoint.x,heldPoint.y));g.flush();assert.equal(g.highlighted,false);assert.equal(g.opened,0);assert.equal(g.timers.size,0);g.cleanup();console.log('PASS app switch cancels pending hold and ignores stale release');
g=setup();g.flush();let branch=g.handles[0];assert.equal(branch.style.touchAction,'none');branch.pointerdown(event(1,100,100));g.canvas.onpointerup(event(1,100,100));assert.equal(branch.clicks,1);assert.equal(g.opened,0);g.cleanup();assert.equal(branch.pointerdown,undefined);console.log('PASS label touch taps open the branch and dispose their listeners');
g=setup();g.flush();branch=g.handles[0];branch.pointerdown(event(1,100,100));g.canvas.onpointermove(event(1,150,100));g.canvas.onpointerup(event(1,150,100));assert.equal(branch.clicks,0);g.cleanup();assert.ok(g.camera.yaw>.18);console.log('PASS dragging from a label rotates without opening it');
g=setup();g.flush();branch=g.handles[0];branch.pointerdown(event(1,100,100));g.canvas.onpointerdown(event(2,200,100));g.canvas.onpointermove(event(2,250,100));g.canvas.onpointerup(event(2,250,100));g.canvas.onpointerup(event(1,100,100));assert.equal(branch.clicks,0);g.cleanup();assert.equal(g.camera.zoom,1.5);console.log('PASS mixed label and canvas touches form one pinch gesture');
g=setup();g.flush();branch=g.handles[0];branch.pointerdown(event(1,100,100));g.canvas.onpointercancel(event(1,100,100));assert.equal(branch.clicks,0);branch.pointerdown(event(2,100,100,'mouse'));g.canvas.onpointerup(event(2,100,100,'mouse'));assert.equal(branch.clicks,0);g.cleanup();console.log('PASS label cancellation does not open and desktop pull remains separate');
for(const type of ['touch','mouse']){g=setup();g.flush();g.canvas.onpointerdown(event(1,100,100,type));g.canvas.onpointermove(event(1,140,120,type));g.cleanup();assert.ok(Math.abs(g.camera.yaw-.42)<1e-12);assert.ok(Math.abs(g.camera.pitch)<1e-12);}console.log('PASS rotation follows input immediately without waiting for easing frames');
g=setup();g.flush();g.canvas.onpointerdown(event(1,100,100));g.canvas.onpointerdown(event(2,101,100));g.canvas.onpointermove(event(2,99,100));g.canvas.onpointermove(event(2,150,100));g.cleanup();assert.equal(g.camera.roll,0);assert.equal(g.camera.zoom,1);console.log('PASS nearly coincident fingers cannot trigger a half-turn or extreme zoom');
g=setup();g.flush();g.canvas.onpointerdown(event(1,100,100));g.canvas.onpointerdown(event(2,200,100));g.canvas.onpointerdown(event(3,400,400));g.canvas.onpointerup(event(1,100,100));g.canvas.onpointermove(event(2,220,100));g.cleanup();assert.equal(g.camera.zoom,1);assert.equal(g.camera.roll,0);assert.ok(Math.abs(g.camera.yaw-.30)<1e-12);console.log('PASS incidental third finger cannot take over the active gesture pair');
g=setup();g.flush();assert.equal(g.canvas.style.touchAction,'none');let e=event(1,100,100);g.canvas.onpointerdown(e);assert.equal(e.prevented,true);e=event(1,100,180);g.canvas.onpointermove(e);assert.equal(e.prevented,true);g.canvas.onpointerup(e);assert.equal(g.opened,0);g.settle();g.cleanup();assert.notEqual(g.camera.pitch,-.12);console.log('PASS vertical touch turns the map and consumes the gesture');
g=setup();g.flush();g.canvas.onpointerdown(event(1,100,100));const second=event(2,200,100);second.isPrimary=false;g.canvas.onpointerdown(second);g.canvas.onpointermove(event(2,300,100));g.canvas.onpointerup(event(2,300,100));g.canvas.onpointerup(event(1,100,100));assert.equal(g.opened,0);g.settle();g.cleanup();assert.equal(g.camera.zoom,2);console.log('PASS secondary touch pinches to zoom without opening a record');
g=setup();g.flush();g.canvas.onpointerdown(event(1,100,100));g.canvas.onpointerdown(event(2,200,100));g.canvas.onpointermove(event(2,5000,100));g.canvas.onpointercancel(event(2,5000,100));g.canvas.onpointermove(event(1,100,150));g.canvas.onpointerup(event(1,100,150));g.settle();g.cleanup();assert.equal(g.camera.zoom,3);assert.equal(g.opened,0);assert.notEqual(g.camera.pitch,-.12);console.log('PASS pinch clamps and cancellation resumes one-finger rotation');
for(const mode of [0,1,2]){g=setup();g.flush();const binding=g.listeners.get('wheel');assert.equal(binding.options.passive,false);e={deltaY:-1,deltaMode:mode,ctrlKey:false,preventDefault(){this.prevented=true}};binding.fn(e);assert.equal(e.prevented,true);g.settle();g.cleanup();assert.ok(g.camera.zoom>1);assert.equal(g.listeners.size,0);}console.log('PASS plain wheel zoom supports all delta modes and removes its listener');
g=setup();g.flush();g.canvas.onpointerdown(event(1,100,100));g.canvas.onlostpointercapture(event(1,100,100));g.canvas.onpointerup(event(1,100,100));assert.equal(g.opened,0);g.cleanup();console.log('PASS lost capture cannot activate a stale tap');

function flick({reduced=false,hold=0,step=16,stop=false}={}){const t=setup(reduced);t.flush();t.canvas.onpointerdown(event(1,100,100));t.advance(16);t.canvas.onpointermove(event(1,140,100));t.flush();t.advance(hold);t.canvas.onpointerup(event(1,140,100));if(stop)t.canvas.onpointerdown(event(2,140,100));for(let i=0;t.frames.size&&i<600;i++)t.flush(step);assert.equal(t.frames.size,0);t.cleanup();return t.camera;}
function pinchRelease(settle){const t=setup();t.flush();t.canvas.onpointerdown(event(1,100,100));t.canvas.onpointerdown(event(2,200,100));t.canvas.onpointermove(event(2,237,100));t.canvas.onpointerup(event(2,237,100));t.canvas.onpointerup(event(1,100,100));if(settle)t.settle();t.cleanup();return t.camera.zoom;}
assert.equal(pinchRelease(false),1.37);assert.equal(pinchRelease(true),1.37);console.log('PASS pinch retains its exact continuous scale without release easing or snapping');
const coast=flick(),held=flick({hold:120});assert.ok(coast.yaw>held.yaw+.05);assert.ok(coast.yaw<held.yaw+1);assert.ok(Math.abs(held.yaw-.42)<.001);console.log('PASS recent release coasts gently and a held release does not fling');
assert.ok(Math.abs(flick({reduced:true}).yaw-.42)<.001);assert.ok(flick({stop:true}).yaw<coast.yaw);console.log('PASS reduced motion and a new touch stop momentum');
assert.ok(Math.abs(flick({step:8}).yaw-flick({step:32}).yaw)<.005);console.log('PASS momentum is consistent across frame rates and settles to idle');
g=setup();g.flush();g.canvas.onpointerdown(event(1,0,0));g.canvas.onpointerdown(event(2,-100,1));g.advance(16);g.canvas.onpointermove(event(2,-100,-1));g.canvas.onpointercancel(event(2,-100,-1));g.canvas.onpointercancel(event(1,0,0));g.settle();g.cleanup();assert.ok(Math.abs(g.camera.roll)>.005&&Math.abs(g.camera.roll)<.05);console.log('PASS two-finger twist crosses the angle boundary without a full-turn jump');
g=setup();g.flush();g.canvas.onpointerdown(event(1,100,100));g.canvas.onpointerdown(event(2,200,100));g.advance(16);g.canvas.onpointermove(event(2,250,150));g.canvas.onpointercancel(event(2,250,150));g.canvas.onpointercancel(event(1,100,100));g.settle();g.cleanup();assert.ok(g.camera.zoom>1);assert.ok(g.camera.roll>0);assert.ok(g.camera.yaw>.18);assert.ok(g.camera.pitch>-.12);console.log('PASS two-finger translation, pinch and twist combine');
g=setup();g.flush();g.canvas.onpointerdown(event(1,100,100));g.advance(16);g.canvas.onpointermove(event(1,150,100));g.canvas.onpointerup(event(1,150,100));g.flush();assert.equal(g.frames.size,1);g.cleanup();assert.equal(g.frames.size,0);console.log('PASS disposal cancels an active coast');

g=setup();g.flush();g.canvas.onpointerdown(event(1,100,100));g.advance(16);g.canvas.onpointermove(event(1,150,100));g.canvas.onpointerup(event(1,150,100));g.flush();const point=g.nodePoint;g.canvas.onpointerdown(event(2,point.x,point.y));g.canvas.onpointerup(event(2,point.x,point.y));assert.equal(g.opened,0);g.settle();g.cleanup();console.log('PASS tapping a node during coasting stops motion without opening it');

g=setup();g.flush();let n=g.nodePoint;g.canvas.onpointerdown(event(1,n.x,n.y));g.advance(349);g.flush(0);assert.equal(g.highlighted,false);g.advance(1);g.flush();assert.equal(g.highlighted,true);g.canvas.onpointerup(event(1,n.x,n.y));g.flush();assert.equal(g.highlighted,false);assert.equal(g.opened,0);g.cleanup();console.log('PASS hold highlights connections after delay and release clears without opening');
g=setup();g.flush();n=g.nodePoint;g.canvas.onpointerdown(event(1,n.x,n.y));g.canvas.onpointermove(event(1,n.x+4,n.y+3));g.advance(360);g.flush();assert.equal(g.highlighted,true);g.canvas.onpointermove(event(1,n.x+30,n.y));g.advance(400);g.flush();assert.equal(g.highlighted,false);assert.equal(g.timers.size,0);g.cleanup();console.log('PASS touch jitter preserves hold while dragging cancels it');
for(const action of ['second','cancel','cleanup']){g=setup();g.flush();n=g.nodePoint;g.canvas.onpointerdown(event(1,n.x,n.y));if(action==='second')g.canvas.onpointerdown(event(2,n.x+50,n.y));else if(action==='cancel')g.canvas.onpointercancel(event(1,n.x,n.y));else g.cleanup();g.advance(400);g.flush();assert.equal(g.highlighted,false);assert.equal(g.timers.size,0);g.cleanup();}console.log('PASS pinch, cancellation and disposal clear pending holds');
g=setup(false,true);g.flush();const before=g.handles.map(h=>[h.style.left,h.style.top]);g.controls.get('#rotate-right').onclick();g.settle();assert.ok(g.handles.some((h,i)=>h.style.left!==before[i][0]||h.style.top!==before[i][1]));for(const h of g.handles){assert.ok(parseFloat(h.style.left)>=4&&parseFloat(h.style.left)<=596);assert.ok(parseFloat(h.style.top)>=30&&parseFloat(h.style.top)<=406)}g.cleanup();console.log('PASS branch anchors rotate with the model and stay within the canvas');
